#!/usr/bin/env python3
"""Sync Script - Merges all memory/data/*.json into a human-readable MEMORY.md file"""

import json
from pathlib import Path
from datetime import datetime

SCRIPT_DIR = Path(__file__).parent.parent
MEMORY_BASE = SCRIPT_DIR / "memory"
DATA_DIR = MEMORY_BASE / "data"
OUTPUT_FILE = MEMORY_BASE.parent / "MEMORY.md"


def safe_json_read(filepath: Path, default={}) -> dict:
    """Safely read JSON with fallback."""
    if not filepath.exists():
        return default()
    
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError) as e:
        print(f"[⚠] Warning: Failed to read {filepath}: {e}")
        return default()


def mask_secret(full_value: str, show_prefix_len: int = 4) -> str:
    """Hide sensitive values in output, showing only prefix."""
    if len(full_value) <= show_prefix_len:
        return "***"
    return full_value[:show_prefix_len] + "***"


def generate_memory_markdown() -> str:
    """Build comprehensive MEMORY.md from all data modules."""
    
    # Load each module
    apis_data = safe_json_read(DATA_DIR / "apis.json", {})
    error_patterns = safe_json_read(DATA_DIR / "error-patterns.json", {})
    network_cfg = safe_json_read(DATA_DIR / "network.json", {})
    token_tips = safe_json_read(DATA_DIR / "token-tips.json", {})
    profiles = safe_json_read(DATA_DIR / "profiles.json", {})
    
    md_lines = [
        "# MEMORY.md - Generated from memory/data/*.json",
        "*Automatically generated by scripts/sync_memory.py*",
        f"*Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
        "",
        "---",
        ""
    ]
    
    # 1. API Configurations Section
    md_lines.append("## 🔌 API Configurations")
    if apis_data and 'apis' in apis_data:
        for api_name, info in apis_data['apis'].items():
            md_lines.append(f"\n### {api_name}")
            md_lines.append(f"- **平台**: {info.get('platform', 'N/A')}")
            md_lines.append(f"- **Base URL**: `{info.get('base_url', 'N/A')}`")
            if 'rate_limit' in info:
                md_lines.append(f"- **限流规则**: {info['rate_limit']}")
            if 'auth_method' in info:
                md_lines.append(f"- **认证方式**: {info['auth_method']}")
            
            # Mask any potential secrets
            if 'key' in info or 'token' in info:
                key_val = info.get('key', info.get('token', ''))
                masked = mask_secret(str(key_val))
                md_lines.append(f"- **Token 前缀**: `{masked}`")
            
            models = info.get('recommended_models', [])[:3]
            if models:
                md_lines.append(f"- **推荐模型**: {', '.join(models)}")
    else:
        md_lines.append("*暂无 API 配置数据*")
    
    # 2. Network/Proxy Rules
    md_lines.append("\n---\n## 🌐 网络代理设置")
    if network_cfg and 'proxy' in network_cfg:
        proxy_info = network_cfg['proxy']
        md_lines.append(f"**SOCKS5 代理**: `{proxy_info.get('url', '172.27.0.1:10080')}`")
        
        if 'usage_rules' in proxy_info:
            md_lines.append("\n**使用规则**:")
            for rule in proxy_info['usage_rules']:
                icon = "✅" if "需要" in rule.get('action', '') else "❌"
                sites = ", ".join(rule.get('sites', []))
                md_lines.append(f"{icon} {rule['action']}: {sites}")
    else:
        md_lines.append("*暂无代理配置*")
    
    # 3. Error Patterns Knowledge Base
    md_lines.append("\n---\n## ❌ 常见错误模式库")
    if error_patterns and 'diagnostic_library' in error_patterns:
        for i, err_entry in enumerate(error_patterns['diagnostic_library'][:5], 1):
            pattern = err_entry.get('pattern', 'Unknown pattern')
            solution = err_entry.get('solution', 'No solution documented')
            severity = err_entry.get('severity', 'medium')
            emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}.get(severity, "⚪")
            
            md_lines.append(f"{i}. **{emoji} {pattern}**")
            md_lines.append(f"   - 严重度：{severity}")
            md_lines.append(f"   - 解决方案：{solution}")
            md_lines.append("")
    else:
        md_lines.append("*暂无错误模式记录*")
    
    # 4. Token Optimization Tips
    md_lines.append("---\n## 💰 Token 优化建议")
    if token_tips and 'optimizations' in token_tips:
        opt_list = token_tips['optimizations']
        md_lines.append("| 技能 | 原消耗 | 优化后 | 节省比例 |")
        md_lines.append("|------|--------|--------|----------|")
        for opt in opt_list[:5]:
            original = opt.get('original_token_usage', '~500')
            optimized = opt.get('optimized_token_usage', '~280')
            skill_name = opt.get('skill_name', 'unknown')
            savings_pct = opt.get('savings', '44%↓')
            md_lines.append(f"| {skill_name} | {original} | {optimized} | {savings_pct} |")
    else:
        md_lines.append("*暂无 Token 优化记录*")
    
    # 5. User Profiles Summary
    md_lines.append("\n---\n## 👤 用户资料索引")
    if profiles and ('identity' in profiles or 'user_profile' in profiles):
        identity = profiles.get('identity', {})
        user_profile = profiles.get('user_profile', {})
        
        if identity:
            md_lines.append("### Agent 身份")
            for k, v in identity.items():
                if k in ['password', 'token']:
                    v = mask_secret(str(v))
                md_lines.append(f"- **{k}**: {v}")
        
        if user_profile:
            md_lines.append("\n### 用户偏好")
            for k, v in user_profile.items():
                if k in ['email', 'address', 'phone']:
                    v = mask_secret(str(v), show_prefix_len=2)
                md_lines.append(f"- **{k}**: {v}")
    else:
        md_lines.append("*用户资料为空（可能存储于 PROFILE.md）*")
    
    # Footer
    md_lines.extend([
        "",
        "---",
        "*本文件由 `scripts/sync_memory.py` 自动生成，手动修改可能会被覆盖*",
        "*原始数据位于 `memory/data/*.json`*"
    ])
    
    return "\n".join(md_lines)


if __name__ == "__main__":
    print("[🔄] Starting memory synchronization...")
    print(f"   Data directory: {DATA_DIR}")
    print(f"   Output file: {OUTPUT_FILE}")
    
    markdown_content = generate_memory_markdown()
    
    OUTPUT_FILE.write_text(markdown_content, encoding='utf-8')
    
    byte_count = len(markdown_content.encode('utf-8'))
    kb_size = byte_count / 1024
    
    print(f"\n[✓] Successfully generated {OUTPUT_FILE.name}")
    print(f"   Size: {byte_count:,} bytes ({kb_size:.1f} KB)")
    print(f"   Lines: {len(markdown_content.splitlines())}")
    
    if DATA_DIR.exists():
        json_files = list(DATA_DIR.glob("*.json"))
        print(f"   Processed {len(json_files)} JSON modules from data/")
    else:
        print(f"\n[!] Note: Data directory does not exist yet. Create it at {DATA_DIR}")
